#服务端口
server:
  port: 8008

#服务名
spring:
  application:
    name: service-statistics

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academy?serverTimezone=GMT%2B8
    username: root
    password: root

  # 返回json的全局时间格式
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/louisblogs/eduservice/mapper/xml/*.xml

