# 服务端口
server:
  port: 8001

# mysql数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academy?serverTimezone=GMT%2B8
    username: root
    password: root

  # 服务名
  application:
    name: service-edu

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # 返回json的全局时间格式
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000

    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/louisblogs/eduservice/mapper/xml/*.xml


#开启熔断机制
#feign:
#  hystrix:
 #   enabled: true
# 设置hystrix超时时间，默认1000ms
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000

# mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置日志级别
#logging:
#  level:
#    root: INFO  #设置全局日志级别，此处默认为info,生产环境可设置为更高级别的warn





